on: [push, pull_request]

name: build

  build:

    runs-on: ubuntu-latest
    name: Build and Test

    steps:

    - name: Checkout code and submodules
      uses: actions/checkout@v4

    - name: Rust/Cargo Cache
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test --verbose
